CREATE TABLE `TIPO_DOCU` (

`CODI_TIPO_DOCU` bigint(64) NOT NULL,

`NOMB_TIPO_DOCU` varchar(50) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_TIPO_DOCU`) ,

UNIQUE INDEX `IDX_TIPO_DOCU` (`CODI_TIPO_DOCU`)

);



CREATE TABLE `UBIC_GEOG` (

`CODI_UBIC_GEOG` bigint(64) NOT NULL,

`NOMB_UBIC_GEOG` varchar(200) NULL,

`CODI_UBIC_GEOG_SUPE` bigint(64) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_UBIC_GEOG`) 

);



CREATE TABLE `VISI` (

`CODI_VISI` bigint(64) NOT NULL COMMENT 'CODIGO DE LA VISITA',

`CODI_USUA` bigint(64) NULL COMMENT 'USUARIO QUE REGISTRA LA VISITA',

`CODI_PERS` bigint(64) NULL COMMENT 'PERSONA QUE HACE LA VISITA',

`CODI_PERS_VISI` bigint(64) NULL COMMENT 'EMPLEADO QUE RECIBE LA VISITA',

`CODI_UNID_ORGA_VISI` bigint(64) NULL COMMENT 'UNIDAD ORGANIZATIVA QUE RECIBE LA VISITA',

`CODI_TIPO_DOCU` bigint(64) NULL,

`CODI_GAFE` bigint(64) NULL COMMENT 'CODIGO DEL GAFETE QUE LO IDENTIFICA',

`CODI_LUGA_ENTR` bigint(64) NULL COMMENT 'CODIGO DEL LUGAR DE ACCESO A LA VISITA',

`CODI_LUGA_SALI` bigint(64) NULL COMMENT 'CODIGO DEL LUGAR DONDE SALE LA VISITA',

`FECH_HORA_ENTR_VISI` datetime NULL COMMENT 'FECHA Y HORA DE LA ENTRADA DE VISITA',

`FECH_HORA_SALI_VISI` datetime NULL COMMENT 'FECHA Y HORA DE LA SALIDA DE VISITA',

`MOTI_VISI` varchar(255) NULL COMMENT 'MOTIVO DE LA VISITA',

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_VISI`) 

);



CREATE TABLE `LUGA_ACCE` (

`CODI_LUGA_ACCE` bigint(64) NOT NULL,

`NOMB_LUGA_ACCE` varchar(100) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_LUGA_ACCE`) 

);



CREATE TABLE `EQUI_COMP` (

`CODI_EQUI_COMP` bigint(64) NOT NULL,

`NOMB_EQUI_COM` varchar(100) NULL,

`CODI_LUGA_ACCE` bigint(64) NULL,

`MAC_ADDR_EQUI_COMP` varchar(50) NULL,

`IP_ADDR_EQUI_COMP` varchar(50) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_EQUI_COMP`) 

);



CREATE TABLE `GAFE_IDEN` (

`CODI_GAFE_IDEN` bigint(64) NOT NULL,

`NOMB_GAFE_IDEN` varchar(200) NULL,

`NUME_TIPO_GAFE` varchar(200) NULL,

`CODI_TIPO_GAFE` bigint(64) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_GAFE_IDEN`) 

);



CREATE TABLE `UNID_ORGA` (

`CODI_UNID_ORGA` bigint(64) NOT NULL,

`NOMB_UNID_ORGA` varchar(100) NULL,

`SIGL_UNID_ORGA` varchar(100) NULL,

`CODI_UNID_ORGA_SUPE` bigint(64) NULL,

`DIRE_UNID_ORGA` varchar(200) NULL,

`TELE_UNID_ORGA` varchar(20) NULL,

`FAX_UNID_ORGA` varchar(20) NULL,

`EMAI_UNID_ORGA` varchar(50) NULL,

`CONT_UNID_ORGA` varchar(100) NULL,

`CODI_UBIC_GEOG` bigint(64) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_UNID_ORGA`) 

);



CREATE TABLE `PERS` (

`CODI_PERS` bigint(64) NOT NULL,

`NOMB_PERS` varchar(255) NULL,

`APEL_PERS` varchar(255) NULL,

`CODI_TIPO_PERS` bigint(64) NULL,

`GENE_PERS` char(1) NULL,

`FECH_NACI_PERS` datetime NULL,

`DUI_PERS` varchar(50) NULL,

`NIT_PERS` varchar(50) NULL,

`TIPO_SANG_PERS` varchar(50) NULL,

`CODI_UBIC_GEOG` bigint(64) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_PERS`) 

);



CREATE TABLE `TIPO_GAFE` (

`CODI_TIPO_GAFE` bigint(64) NOT NULL,

`NOMB_TIPO_GAFE` varchar(200) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_TIPO_GAFE`) 

);



CREATE TABLE `TIPO_PERS` (

`CODI_TIPO_PERS` bigint(64) NOT NULL,

`NOMB_TIPO_PERS` varchar(150) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_TIPO_PERS`) 

);



CREATE TABLE `PERS_HIST` (

`CODI_PERS_HIST` bigint(64) NOT NULL,

`CODI_PERS` bigint(64) NULL,

`NOMB_PERS` varchar(255) NULL,

`APEL_PERS` varchar(255) NULL,

`CODI_TIPO_PERS` bigint(64) NULL,

`CODI_UBIC_GEOG` bigint(64) NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_PERS_HIST`) 

);



CREATE TABLE `USUA` (

`CODI_USUA` bigint(64) NOT NULL,

`CODI_PERS` bigint(64) NULL,

`ACCE_USUA` varchar(255) NULL,

`CONT_USUA` varchar(255) NULL,

`FECH_CAMB_CLAV_USUA` datetime NULL,

`FECH_ALTA` datetime NULL,

`FECH_BAJA` datetime NULL,

`ESTA` longblob NULL,

PRIMARY KEY (`CODI_USUA`) 

);





ALTER TABLE `GAFE_IDEN` ADD CONSTRAINT `FK_GAFEIDEN_TIPOIDEN` FOREIGN KEY (`CODI_TIPO_GAFE`) REFERENCES `TIPO_GAFE` (`CODI_TIPO_GAFE`);

ALTER TABLE `UNID_ORGA` ADD CONSTRAINT `FK_UNIDORGA_UNIDORGA` FOREIGN KEY (`CODI_UNID_ORGA_SUPE`) REFERENCES `UNID_ORGA` (`CODI_UNID_ORGA`);

ALTER TABLE `EQUI_COMP` ADD CONSTRAINT `FK_EQUICOMP_LUGAACCE` FOREIGN KEY (`CODI_LUGA_ACCE`) REFERENCES `LUGA_ACCE` (`CODI_LUGA_ACCE`);

ALTER TABLE `UBIC_GEOG` ADD CONSTRAINT `FK_UBICGEOG_UBICGEOG` FOREIGN KEY (`CODI_UBIC_GEOG_SUPE`) REFERENCES `UBIC_GEOG` (`CODI_UBIC_GEOG`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_LUGAACCE_ENTR` FOREIGN KEY (`CODI_LUGA_ENTR`) REFERENCES `LUGA_ACCE` (`CODI_LUGA_ACCE`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_LUGAACCE_SALI` FOREIGN KEY (`CODI_LUGA_SALI`) REFERENCES `LUGA_ACCE` (`CODI_LUGA_ACCE`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_GAFEINDEN` FOREIGN KEY (`CODI_GAFE`) REFERENCES `GAFE_IDEN` (`CODI_GAFE_IDEN`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_UNIDORGA` FOREIGN KEY (`CODI_UNID_ORGA_VISI`) REFERENCES `UNID_ORGA` (`CODI_UNID_ORGA`);

ALTER TABLE `UNID_ORGA` ADD CONSTRAINT `FK_UNIDORGA_UBICGEOG` FOREIGN KEY (`CODI_UBIC_GEOG`) REFERENCES `UBIC_GEOG` (`CODI_UBIC_GEOG`);

ALTER TABLE `PERS` ADD CONSTRAINT `FK_PERS_TIPOPERS` FOREIGN KEY (`CODI_TIPO_PERS`) REFERENCES `TIPO_PERS` (`CODI_TIPO_PERS`);

ALTER TABLE `PERS_HIST` ADD CONSTRAINT `FK_PERSHIST_PERS` FOREIGN KEY (`CODI_PERS`) REFERENCES `PERS` (`CODI_PERS`);

ALTER TABLE `PERS_HIST` ADD CONSTRAINT `FK_PERSHIST_TIPOPERS` FOREIGN KEY (`CODI_TIPO_PERS`) REFERENCES `TIPO_PERS` (`CODI_TIPO_PERS`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_PERSHIST_USUA` FOREIGN KEY (`CODI_USUA`) REFERENCES `USUA` (`CODI_USUA`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_PERSHIST_PERS` FOREIGN KEY (`CODI_PERS`) REFERENCES `PERS_HIST` (`CODI_PERS_HIST`);

ALTER TABLE `VISI` ADD CONSTRAINT `FK_VISI_TIPODOCU` FOREIGN KEY (`CODI_TIPO_DOCU`) REFERENCES `TIPO_DOCU` (`CODI_TIPO_DOCU`);

ALTER TABLE `USUA` ADD CONSTRAINT `FK_USUA_PERS` FOREIGN KEY (`CODI_PERS`) REFERENCES `PERS` (`CODI_PERS`);



-- Primera consulta

SELECT v.CODI_VISI AS '# de visita', v.CODI_UNID_ORGA_VISI AS '# de unidad', u.NOMB_UNID_ORGA AS 'Unidad',
 v.MOTI_VISI AS 'Motivo', v.FECH_HORA_ENTR_VISI AS 'Fecha/hora entrada', v.FECH_HORA_SALI_VISI AS 'Fecha/hora salida' 
 FROM visi v INNER JOIN unid_orga u ON v.CODI_UNID_ORGA_VISI = u.CODI_UNID_ORGA
 WHERE CODI_UNID_ORGA = 1
 
-- segunda consulta
SELECT l.NOMB_LUGA_ACCE, v.FECH_HORA_ENTR_VISI, v.FECH_HORA_SALI_VISI, u.NOMB_UNID_ORGA 
from visi v 
INNER JOIN luga_acce l 
ON v.CODI_LUGA_ENTR = l.CODI_LUGA_ACCE INNER JOIN unid_orga u ON v.CODI_UNID_ORGA_VISI = u.CODI_UNID_ORGA 
INNER JOIN pers p ON v.CODI_PERS = p.CODI_PERS WHERE v.CODI_PERS = 1

-- tercera consulta 
-- WHERE `miCampoFecha` BETWEEN 'fechaMin'  AND 'fechaMax';

SELECT
     unid_orga.`CODI_UNID_ORGA` AS unid_orga_CODI_UNID_ORGA,
     unid_orga.`NOMB_UNID_ORGA` AS unid_orga_NOMB_UNID_ORGA,
     visi.`FECH_HORA_ENTR_VISI` AS visi_FECH_HORA_ENTR_VISI,
     visi.`FECH_HORA_SALI_VISI` AS visi_FECH_HORA_SALI_VISI,
     visi.`MOTI_VISI` AS visi_MOTI_VISI
FROM
     `unid_orga` unid_orga INNER JOIN `visi` visi ON unid_orga.`CODI_UNID_ORGA` = visi.`CODI_UNID_ORGA_VISI`
WHERE CAST(`FECH_HORA_ENTR_VISI` AS DATE) BETWEEN '2016-08-03 21:00:04'  AND '2016-08-06 21:00:06'; 
